### ISSUE TITLE
Basic Objects Design

### ISSUE THREAD

**Issue by consome** [Nysm-Inc/philand-demo#19]
Scope 
- Token id 1-16 (including design and upload arwearve)
https://docs.google.com/spreadsheets/d/1XnFYResppcSTgRuqI_YAZUGmzd_ioTa-RS312Z0RLE8/edit#gid=0
- Object Contract 
- Transaction fee Fix(loyalty)
- Condition is verified by L1 testnet

**Comment by ZaK3939** [comment]
https://docs.google.com/spreadsheets/d/1XnFYResppcSTgRuqI_YAZUGmzd_ioTa-RS312Z0RLE8/edit#gid=0
