### ISSUE TITLE
Basic Landing Page

### ISSUE THREAD

**Issue by consome** [Nysm-Inc/philand-demo#26]
Scope 
- Hosting landing page
- Custom Domain 
- Design FIx
- Audio 
- Mobile View
- Status Panel
 - Favicon
 - OGP

**Comment by consome** [comment]
FIgma : https://www.figma.com/file/EN7PLRziTQU22FNYgxzgJz/%E2%93%8F-PHI?node-id=0%3A1

**Comment by ZaK3939** [comment]
![Cursor_と_Ⓩ_PHI_–_Figma.png](https://images.zenhubusercontent.com/613d642f6d31a51180526f7b/36340cb8-c617-496a-9b99-cd71a813ad34)
