### ISSUE TITLE
Next Object Plan For Sprint3

### ISSUE THREAD

**Issue by ZaK3939** [Nysm-Inc/philand-demo#88]
Scope
- Planning Object strategy

**Comment by ZaK3939** [comment]
https://docs.google.com/spreadsheets/d/1XnFYResppcSTgRuqI_YAZUGmzd_ioTa-RS312Z0RLE8/edit#gid=64367103

**Comment by shugotsuji** [comment]
- 100 ETH Holding
- 300 ETH Holding 
- 500 ETH Holding 
- 1000 ETH Holding
- Staking 50 ETH on Lido
- Staking 100 ETH on Lido
- Staking 500 ETH on Lido
- Staking 1000 ETH on Lido
- Lens Protocol Profile Owner
- Issuing 1 Article NFT on Mirror
- 1 Nouns Holding
- Bankless DAO(Voting, Token?)
- Gitcoin(Voting, Token?)
